name: Build &  Deploy to Firebase
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        env:
<<<<<<< Updated upstream
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          VUE_APP_BUTTER_API_KEY: ${{ secrets.VUE_APP_BUTTER_API_KEY }}
=======
          VUE_APP_BUTTER_CMS_READ_API_KEY: ${{ secrets.BUTTER_CMS_READ_API_KEY }}
>>>>>>> Stashed changes
          VUE_APP_YAHOO_CLIENT_KEY: ${{ secrets.VUE_APP_YAHOO_CLIENT_KEY }}
          VUE_APP_YAHOO_CLIENT_SECRET: ${{ secrets.VUE_APP_YAHOO_CLIENT_SECRET }}
          VUE_APP_GOOG_CLIENT_KEY: ${{ secrets.VUE_APP_GOOG_CLIENT_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_DATABASE_URL }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_BLUEFIRE }}'
          channelId: live
          projectId: project-bluefire
